services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - api_data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_GRAPHQL_URL=http://localhost:8080/graphql
      - VITE_GRAPHQL_WS_URL=ws://localhost:8080/graphql
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  api_data: